language: node_js
sudo: false
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
  - "16"
  - "node"

cache: npm

matrix:
  fast_finish: true
  allow_failures:
    - node_js: node

script:
  - npm run lint
  - npm run test-and-coverage

after_success:
  - cat ./coverage/lcov.info | codacy-coverage
  - codecov
