module.exports = {
  UNKNOWN: 'unknown',
  BROWSER: 'browser',
  BROWSER_TEXT: 'browser:text',
  APP: 'app',
  APP_EMAIL: 'app:email',
  APP_GAME: 'app:game',
  APP_MEDIAPLAYER: 'app:mediaplayer',
  APP_FEEDREADER: 'app:feedreader',
  APP_PODCAST: 'app:podcast',
  APP_SOCIAL: 'app:social',
  APP_OFFICE: 'app:office',
  APP_EDITOR: 'app:editor',
  APP_DOWNLOAD: 'app:download',
  APP_SEARCH: 'app:search',
  APP_NEWS: 'app:news',
  APP_ANTIVIRUS: 'app:antivirus',
  APP_SHOPPING: 'app:shopping',
  APP_CHAT: 'app:chat',
};
