module.exports = {
  DESKTOP: 'desktop',
  MOBILE: 'mobile',
  PDA: 'pda',
  DECT: 'dect',
  TABLET: 'tablet',
  GAMING: 'gaming',
  EREADER: 'ereader',
  MEDIA: 'media',
  HEADSET: 'headset',
  WATCH: 'watch',
  EMULATOR: 'emulator',
  TELEVISION: 'television',
  MONITOR: 'monitor',
  CAMERA: 'camera',
  PRINTER: 'printer',
  SIGNAGE: 'signage',
  WHITEBOARD: 'whiteboard',
  DEVBOARD: 'devboard',
  INFLIGHT: 'inflight',
  APPLIANCE: 'appliance',
  GPS: 'gps',
  CAR: 'car',
  POS: 'pos',
  BOT: 'bot',
  PROJECTOR: 'projector',
};
