name: Build and test
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "6.x"
          - "7.x"
          - "8.x"
          - "9.x"
          - "10.x"
          - "11.x"
          - "12.x"
          - "13.x"
          - "14.x"
          - "15.x"
          - "16.x"
    steps:
      - name: "Set up Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node-version }}"
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint
      - run: npm run test-and-coverage
